# Generated by Django 4.1.3 on 2022-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='is_available_on_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='is_available_on_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='is_available_on_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='is_available_on_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='is_available_on_wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
